backend:
  name: github
  repo: Denzor19/website-oneiro
  branch: main
  auth_token: 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
media_folder: "images"
public_folder: "/images"

collections:
  - name: "menu"
    label: "Menu"
    files:
      - label: "Menu Items"
        name: "menu_items"
        file: "data/menu.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Enabled", name: "enabled", widget: "boolean", default: true }
              - { label: "Category", name: "category", widget: "select", options: ["Pizza", "Fish", "Pasta", "Fries"] }
              - { label: "Image", name: "image", widget: "string" }
